apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pull down the foundation blueprints automatically
resources:
- ../../base

# Explicitly tracking image tag patches natively via Kustomize CLI engine
images:
- name: ghcr.io/amarpal-singh5/kubernetes-gitops-platform
  newName: ghcr.io/amarpal-singh5/kubernetes-gitops-platform
  newTag: bdb9e061c1d4f6a6987d8d732b02b128dbcf2e3e
