apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-gitops-platform

spec:
  replicas: 3

  selector:
    matchLabels:
      app: kubernetes-gitops-platform

  template:
    metadata:
      labels:
        app: kubernetes-gitops-platform

    spec:
      containers:
        - name: kubernetes-gitops-platform
          image: ghcr.io/amarpal-singh5/kubernetes-gitops-platform:e27a41cb7abb584f9a3c49af25dae93065ffb466
          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
