apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-lab
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/amarpal-singh5/github-actions-lab.git
    targetRevision: main
    path: gitops

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
