apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-lab

spec:
  replicas: 3

  selector:
    matchLabels:
      app: github-actions-lab

  template:
    metadata:
      labels:
        app: github-actions-lab

    spec:
      containers:
        - name: github-actions-lab
          image: ghcr.io/amarpal-singh5/github-actions-lab:b231df218c8bca8c8978f6409b54078fb028837c
          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
